language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential libpoppler-cpp-dev pkg-config python-dev
- ./ci/setup.sh "${DOCKER_PLATFORMS}"

sudo: true
dist: xenial

services:
  - docker
  
addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/arm/v6,linux/arm64/v8"
    - BUILDKIT_HOST=tcp://0.0.0.0:1234
    - DOCKER_CLI_EXPERIMENTAL=enabled


matrix:
    include:
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7-dev"
        - env:
            - BUILD_DOCKER=1
            # Variable to add to publish the Docker image:
            # * DOCKER_USERNAME
            # * DOCKER_PASSWORD, to be encrypted, use `travis encrypt DOCKER_PASSWORD=<password>`
          services:
            - docker
          before_install:
            - true
          install:
            - true
          script:
            - docker build --tag=the-paperless-project/paperless .
          after_success:
            - true
    
jobs:
  include:
    - script: >
        ./ci/build.sh \
          "${DOCKER_IMAGE}" \
          "${DOCKER_COMMIT}" \
          "${DOCKER_PLATFORMS}"

install:
    - pip install --upgrade pip pipenv sphinx
    - pipenv lock -vv -r > requirements.txt
    - pip install -r requirements.txt

script:
    - cd src/
    - pytest --cov
    - pycodestyle
    - sphinx-build -b html ../docs ../docs/_build -W

after_success:
  - coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      tags: true
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      branch: master
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    script: >-
      bash ./ci/push.sh
      "${DOCKER_IMAGE}"
      "${DOCKER_COMMIT}"
      "${DOCKER_TAG}"
      "${DOCKER_PLATFORMS}"
    on:
      tags: true
